import { Recipe } from "./types";

const SAMPLE_RECIPES: Recipe[] = [
  {
    id: 1,
    name: "Overnight Oats with Berries",
    type: "breakfast",
    ingredients: [
      { name: "rolled oats", quantity:"1/2 cup" },
      { name: "almond milk", quantity:"1/2 cup" },
      { name: "chia seeds", quantity:"1 tbsp" },
      { name: "honey", quantity:"1 tsp" },
      { name: "mixed berries", quantity:"1/4 cup" },
      { name: "vanilla extract", quantity:"1/4 tsp" },
    ],
    instructions: [
      "In a jar or bowl, combine oats, chia seeds, and vanilla extract.",
      "Pour in almond milk and stir well to combine all ingredients.",
      "Add honey and stir again until evenly distributed.",
      "Cover and refrigerate overnight or for at least 4 hours.",
      "In the morning, stir the oats and top with fresh mixed berries.",
      "Enjoy cold or let sit at room temperature for 10 minutes before eating.",
    ],
    cookTime: 5,
    servings: 1,
    difficulty: "Easy",
    description:
      "A healthy and delicious breakfast that requires no cooking. Perfect for busy mornings!",
    tags: ["Healthy", "Quick", "Make-ahead", "Vegetarian"],
    isFavorite: true,
  },
  {
    id: 2,
    name: "Mediterranean Quinoa Bowl",
    type: "lunch",
    ingredients: [
      { name: "quinoa", quantity:"1 cup" },
      { name: "vegetable broth", quantity:"2 cups" },
      { name: "cucumber diced", quantity:"1" },
      { name: "cherry tomatoes", quantity:"1 cup" },
      { name: "red onion", quantity:"1/4" },
      { name: "olives", quantity:"1/2 cup" },
      { name: "feta cheese", quantity:"4 oz" },
      { name: "olive oil", quantity:"2 tbsp" },
      { name: "lemon juiced", quantity:"1" },
    ],
    instructions: [
      "Cook quinoa in vegetable broth according to package directions.",
      "While quinoa cooks, dice cucumber and halve cherry tomatoes.",
      "Slice red onion thinly and crumble feta cheese.",
      "Once quinoa is cooked, let it cool for 10 minutes.",
      "Combine all vegetables with cooled quinoa in a large bowl.",
      "Drizzle with olive oil and lemon juice, then toss gently.",
      "Top with crumbled feta and serve immediately.",
    ],
    cookTime: 20,
    servings: 2,
    difficulty: "Easy",
    description:
      "Fresh and nutritious Mediterranean-inspired bowl packed with vegetables and protein.",
    tags: ["Healthy", "Vegetarian", "High Protein", "Mediterranean"],
    isFavorite: false,
  },
  {
    id: 3,
    name: "Honey Garlic Salmon",
    type: "dinner",
    ingredients: [
      { name: "salmon fillets", quantity: "2" },
      { name: "honey", quantity: "3 tbsp" },
      { name: "soy sauce", quantity: "2 tbsp" },
      { name: "garlic minced", quantity: "3 cloves" },
      { name: "ginger grated", quantity: "1 tsp" },
      { name: "jasmine rice", quantity: "1 cup" },
      { name: "broccoli florets", quantity: "2 cups" },
    ],
    instructions: [
      "Preheat oven to 400°F and line a baking sheet with parchment paper.",
      "Cook rice according to package directions.",
      "Mix honey, soy sauce, minced garlic, and grated ginger in a small bowl.",
      "Place salmon fillets on prepared baking sheet and brush with half the glaze.",
      "Bake for 12-15 minutes until salmon flakes easily with a fork.",
      "Meanwhile, steam broccoli for 4-5 minutes until tender-crisp.",
      "Brush salmon with remaining glaze and serve over rice with steamed broccoli.",
    ],
    cookTime: 25,
    servings: 2,
    difficulty: "Medium",
    description:
      "Perfectly glazed salmon with a sweet and savory honey garlic sauce.",
    tags: ["High Protein", "Gluten-free", "Healthy"],
    isFavorite: false,
  },
  {
    id: 4,
    name: "Avocado Toast Deluxe",
    type: "breakfast",
    ingredients: [
      { name: "sourdough bread", quantity: "2 slices" },
      { name: "ripe avocado", quantity: "1" },
      { name: "cherry tomatoes", quantity: "4-5" },
      { name: "feta cheese", quantity: "2 oz" },
      { name: "everything bagel seasoning", quantity: "1 tsp" },
      { name: "lemon", quantity: "1/2" },
    ],
    instructions: [
      "Toast sourdough bread slices until golden brown.",
      "Mash avocado in a bowl with a squeeze of lemon juice.",
      "Slice cherry tomatoes in half and crumble feta cheese.",
      "Spread mashed avocado evenly on toast slices.",
      "Top with halved cherry tomatoes and crumbled feta.",
      "Sprinkle everything bagel seasoning on top and serve immediately.",
    ],
    cookTime: 5,
    servings: 1,
    difficulty: "Easy",
    description:
      "Elevated avocado toast with fresh toppings and a burst of flavor.",
    tags: ["Quick", "Vegetarian", "Healthy"],
    isFavorite: false,
  },
  {
    id: 5,
    name: "Thai-Style Chicken Curry",
    type: "dinner",
    ingredients: [
      { name: "chicken thighs cut in pieces", quantity: "1 lb" },
      { name: "coconut milk", quantity: "1 can" },
      { name: "red curry paste", quantity: "3 tbsp" },
      { name: "bell pepper sliced", quantity: "1" },
      { name: "bamboo shoots", quantity: "1 cup" },
      { name: "Thai basil leaves", quantity: "1/2 cup" },
      { name: "jasmine rice", quantity: "2 cups" },
    ],
    instructions: [
      "Cook jasmine rice according to package directions and keep warm.",
      "Heat a large skillet over medium-high heat and add chicken pieces.",
      "Cook chicken for 5-6 minutes until browned on all sides.",
      "Add red curry paste and stir for 1 minute until fragrant.",
      "Pour in coconut milk and bring to a gentle simmer.",
      "Add bell pepper and bamboo shoots, simmer for 15-20 minutes.",
      "Stir in Thai basil leaves and cook for 2 more minutes.",
      "Serve hot over jasmine rice.",
    ],
    cookTime: 35,
    servings: 4,
    difficulty: "Medium",
    description:
      "Aromatic and creamy Thai curry with tender chicken and vegetables.",
    tags: ["Spicy", "Asian", "High Protein"],
    isFavorite: false,
  },
  {
    id: 6,
    name: "Greek Yogurt Parfait",
    type: "breakfast",
    ingredients: [
      { name: "Greek yogurt", quantity: "1 cup" },
      { name: "granola", quantity: "1/4 cup" },
      { name: "mixed berries", quantity: "1/2 cup" },
      { name: "honey", quantity: "1 tbsp" },
      { name: "fresh mint leaves", quantity: "4-5" },
    ],
    instructions: [
      "Layer half the Greek yogurt in the bottom of a glass or bowl.",
      "Add half the mixed berries over the yogurt layer.",
      "Drizzle with half the honey evenly.",
      "Add a layer of granola for crunch.",
      "Repeat layers with remaining yogurt, berries, and honey.",
      "Top with fresh mint leaves and serve immediately.",
    ],
    cookTime: 3,
    servings: 1,
    difficulty: "Easy",
    description:
      "Protein-rich breakfast parfait with layers of creamy yogurt and crunchy granola.",
    tags: ["Quick", "High Protein", "Healthy", "Vegetarian"],
    isFavorite: true,
  },
];

const TAGS = [
  "Vegetarian",
  "Vegan",
  "Gluten-Free",
  "Quick",
  "Healthy",
  "Dessert",
  "Spicy",
  "Low-Carb",
];

export { SAMPLE_RECIPES, TAGS };
