import { Recipe } from "./types";

const SAMPLE_RECIPES: Recipe[] = [
  {
    id: 1,
    name: "Overnight Oats with Berries",
    type: "breakfast",
    ingredients: [
      { name: "rolled oats", quantity:"1/2 cup" },
      { name: "almond milk", quantity:"1/2 cup" },
      { name: "chia seeds", quantity:"1 tbsp" },
      { name: "honey", quantity:"1 tsp" },
      { name: "mixed berries", quantity:"1/4 cup" },
      { name: "vanilla extract", quantity:"1/4 tsp" },
    ],
    instructions: [
      "In a jar or bowl, combine oats, chia seeds, and vanilla extract.",
      "Pour in almond milk and stir well to combine all ingredients.",
      "Add honey and stir again until evenly distributed.",
      "Cover and refrigerate overnight or for at least 4 hours.",
      "In the morning, stir the oats and top with fresh mixed berries.",
      "Enjoy cold or let sit at room temperature for 10 minutes before eating.",
    ],
    cookTime: 5,
    servings: 1,
    difficulty: "Easy",
    description:
      "A healthy and delicious breakfast that requires no cooking. Perfect for busy mornings!",
    tags: ["Healthy", "Quick", "Make-ahead", "Vegetarian"],
    isFavorite: true,
  },
  {
    id: 2,
    name: "Mediterranean Quinoa Bowl",
    type: "lunch",
    ingredients: [
      { name: "quinoa", quantity:"1 cup" },
      { name: "vegetable broth", quantity:"2 cups" },
      { name: "cucumber diced", quantity:"1" },
      { name: "cherry tomatoes", quantity:"1 cup" },
      { name: "red onion", quantity:"1/4" },
      { name: "olives", quantity:"1/2 cup" },
      { name: "feta cheese", quantity:"4 oz" },
      { name: "olive oil", quantity:"2 tbsp" },
      { name: "lemon juiced", quantity:"1" },
    ],
    instructions: [
      "Cook quinoa in vegetable broth according to package directions.",
      "While quinoa cooks, dice cucumber and halve cherry tomatoes.",
      "Slice red onion thinly and crumble feta cheese.",
      "Once quinoa is cooked, let it cool for 10 minutes.",
      "Combine all vegetables with cooled quinoa in a large bowl.",
      "Drizzle with olive oil and lemon juice, then toss gently.",
      "Top with crumbled feta and serve immediately.",
    ],
    cookTime: 20,
    servings: 2,
    difficulty: "Easy",
    description:
      "Fresh and nutritious Mediterranean-inspired bowl packed with vegetables and protein.",
    tags: ["Healthy", "Vegetarian", "High Protein", "Mediterranean"],
    isFavorite: false,
  },
  {
    id: 3,
    name: "Honey Garlic Salmon",
    type: "dinner",
    ingredients: [
      { name: "salmon fillets", quantity: "2" },
      { name: "honey", quantity: "3 tbsp" },
      { name: "soy sauce", quantity: "2 tbsp" },
      { name: "garlic minced", quantity: "3 cloves" },
      { name: "ginger grated", quantity: "1 tsp" },
      { name: "jasmine rice", quantity: "1 cup" },
      { name: "broccoli florets", quantity: "2 cups" },
    ],
    instructions: [
      "Preheat oven to 400°F and line a baking sheet with parchment paper.",
      "Cook rice according to package directions.",
      "Mix honey, soy sauce, minced garlic, and grated ginger in a small bowl.",
      "Place salmon fillets on prepared baking sheet and brush with half the glaze.",
      "Bake for 12-15 minutes until salmon flakes easily with a fork.",
      "Meanwhile, steam broccoli for 4-5 minutes until tender-crisp.",
      "Brush salmon with remaining glaze and serve over rice with steamed broccoli.",
    ],
    cookTime: 25,
    servings: 2,
    difficulty: "Medium",
    description:
      "Perfectly glazed salmon with a sweet and savory honey garlic sauce.",
    tags: ["High Protein", "Gluten-free", "Healthy"],
    isFavorite: false,
  },
  {
    id: 4,
    name: "Avocado Toast Deluxe",
    type: "breakfast",
    ingredients: [
      { name: "sourdough bread", quantity: "2 slices" },
      { name: "ripe avocado", quantity: "1" },
      { name: "cherry tomatoes", quantity: "4-5" },
      { name: "feta cheese", quantity: "2 oz" },
      { name: "everything bagel seasoning", quantity: "1 tsp" },
      { name: "lemon", quantity: "1/2" },
    ],
    instructions: [
      "Toast sourdough bread slices until golden brown.",
      "Mash avocado in a bowl with a squeeze of lemon juice.",
      "Slice cherry tomatoes in half and crumble feta cheese.",
      "Spread mashed avocado evenly on toast slices.",
      "Top with halved cherry tomatoes and crumbled feta.",
      "Sprinkle everything bagel seasoning on top and serve immediately.",
    ],
    cookTime: 5,
    servings: 1,
    difficulty: "Easy",
    description:
      "Elevated avocado toast with fresh toppings and a burst of flavor.",
    tags: ["Quick", "Vegetarian", "Healthy"],
    isFavorite: false,
  },
  {
    id: 5,
    name: "Thai-Style Chicken Curry",
    type: "dinner",
    ingredients: [
      { name: "chicken thighs cut in pieces", quantity: "1 lb" },
      { name: "coconut milk", quantity: "1 can" },
      { name: "red curry paste", quantity: "3 tbsp" },
      { name: "bell pepper sliced", quantity: "1" },
      { name: "bamboo shoots", quantity: "1 cup" },
      { name: "Thai basil leaves", quantity: "1/2 cup" },
      { name: "jasmine rice", quantity: "2 cups" },
    ],
    instructions: [
      "Cook jasmine rice according to package directions and keep warm.",
      "Heat a large skillet over medium-high heat and add chicken pieces.",
      "Cook chicken for 5-6 minutes until browned on all sides.",
      "Add red curry paste and stir for 1 minute until fragrant.",
      "Pour in coconut milk and bring to a gentle simmer.",
      "Add bell pepper and bamboo shoots, simmer for 15-20 minutes.",
      "Stir in Thai basil leaves and cook for 2 more minutes.",
      "Serve hot over jasmine rice.",
    ],
    cookTime: 35,
    servings: 4,
    difficulty: "Medium",
    description:
      "Aromatic and creamy Thai curry with tender chicken and vegetables.",
    tags: ["Spicy", "Asian", "High Protein"],
    isFavorite: false,
  },
  {
    id: 6,
    name: "Greek Yogurt Parfait",
    type: "breakfast",
    ingredients: [
      { name: "Greek yogurt", quantity: "1 cup" },
      { name: "granola", quantity: "1/4 cup" },
      { name: "mixed berries", quantity: "1/2 cup" },
      { name: "honey", quantity: "1 tbsp" },
      { name: "fresh mint leaves", quantity: "4-5" },
    ],
    instructions: [
      "Layer half the Greek yogurt in the bottom of a glass or bowl.",
      "Add half the mixed berries over the yogurt layer.",
      "Drizzle with half the honey evenly.",
      "Add a layer of granola for crunch.",
      "Repeat layers with remaining yogurt, berries, and honey.",
      "Top with fresh mint leaves and serve immediately.",
    ],
    cookTime: 3,
    servings: 1,
    difficulty: "Easy",
    description:
      "Protein-rich breakfast parfait with layers of creamy yogurt and crunchy granola.",
    tags: ["Quick", "High Protein", "Healthy", "Vegetarian"],
    isFavorite: true,
  },
  {
    id: 7,
    name: "Avocado Toast",
    type: "breakfast",
    ingredients: [
      { name: "sourdough bread", quantity: "2 slices" },
      { name: "ripe avocado", quantity: "1" },
      { name: "lemon juice", quantity: "1 tsp" },
      { name: "chili flakes", quantity: "1/4 tsp" },
      { name: "olive oil", quantity: "1 tsp" },
    ],
    instructions: [
      "Toast sourdough slices until golden brown.",
      "Mash avocado with lemon juice and spread over toast.",
      "Drizzle with olive oil and sprinkle chili flakes.",
      "Serve immediately."
    ],
    cookTime: 5,
    servings: 1,
    difficulty: "Easy",
    description: "Simple and nutritious breakfast toast with creamy avocado and a kick of spice.",
    tags: ["Quick", "Healthy", "Vegan", "Breakfast"],
    isFavorite: false,
  },
  {
    id: 8,
    name: "Spaghetti Carbonara",
    type: "dinner",
    ingredients: [
      { name: "spaghetti", quantity: "200g" },
      { name: "egg yolks", quantity: "2" },
      { name: "parmesan cheese", quantity: "50g" },
      { name: "pancetta", quantity: "100g" },
      { name: "black pepper", quantity: "to taste" },
    ],
    instructions: [
      "Cook spaghetti in salted boiling water until al dente.",
      "Fry pancetta until crispy.",
      "Whisk egg yolks with parmesan cheese.",
      "Drain pasta and combine with pancetta and egg mixture.",
      "Season generously with black pepper and serve."
    ],
    cookTime: 20,
    servings: 2,
    difficulty: "Medium",
    description: "Classic Italian pasta with a creamy egg-based sauce and crispy pancetta.",
    tags: ["Italian", "Quick", "Comfort Food"],
    isFavorite: true,
  },
  {
    id: 9,
    name: "Chicken Stir-Fry",
    type: "dinner",
    ingredients: [
      { name: "chicken breast", quantity: "250g" },
      { name: "soy sauce", quantity: "2 tbsp" },
      { name: "broccoli florets", quantity: "1 cup" },
      { name: "red bell pepper", quantity: "1" },
      { name: "garlic cloves", quantity: "2" },
    ],
    instructions: [
      "Slice chicken into thin strips.",
      "Stir-fry chicken in hot oil until golden.",
      "Add garlic, broccoli, and bell pepper, cook until tender-crisp.",
      "Stir in soy sauce and cook 2 more minutes.",
      "Serve hot over rice."
    ],
    cookTime: 15,
    servings: 2,
    difficulty: "Easy",
    description: "Quick Asian-inspired stir-fry with tender chicken and fresh vegetables.",
    tags: ["Quick", "Healthy", "Asian", "One-Pan"],
    isFavorite: false,
  },
  {
    id: 10,
    name: "Miso Soup",
    type: "lunch",
    ingredients: [
      { name: "dashi stock", quantity: "3 cups" },
      { name: "miso paste", quantity: "2 tbsp" },
      { name: "tofu cubes", quantity: "1/2 cup" },
      { name: "wakame seaweed", quantity: "2 tbsp" },
      { name: "green onions", quantity: "2 stalks" },
    ],
    instructions: [
      "Heat dashi stock in a saucepan.",
      "Add wakame and tofu cubes, simmer 2 minutes.",
      "Dissolve miso paste in a ladle of hot broth, then stir back in.",
      "Garnish with green onions and serve warm."
    ],
    cookTime: 10,
    servings: 2,
    difficulty: "Easy",
    description: "Traditional Japanese soup with miso, tofu, and seaweed.",
    tags: ["Japanese", "Soup", "Light", "Healthy"],
    isFavorite: true,
  },
  {
    id: 11,
    name: "Caprese Salad",
    type: "dinner",
    ingredients: [
      { name: "tomatoes", quantity: "2 large" },
      { name: "fresh mozzarella", quantity: "125g" },
      { name: "fresh basil leaves", quantity: "1 handful" },
      { name: "balsamic glaze", quantity: "2 tsp" },
      { name: "olive oil", quantity: "1 tbsp" },
    ],
    instructions: [
      "Slice tomatoes and mozzarella into even rounds.",
      "Arrange alternating slices on a plate.",
      "Top with basil leaves, drizzle with olive oil and balsamic glaze.",
      "Serve immediately."
    ],
    cookTime: 5,
    servings: 2,
    difficulty: "Easy",
    description: "Fresh Italian salad of tomato, mozzarella, and basil.",
    tags: ["Italian", "Vegetarian", "Quick", "Healthy"],
    isFavorite: false,
  },
  {
    id: 12,
    name: "Beef Tacos",
    type: "dinner",
    ingredients: [
      { name: "ground beef", quantity: "250g" },
      { name: "taco seasoning", quantity: "2 tbsp" },
      { name: "taco shells", quantity: "6" },
      { name: "shredded lettuce", quantity: "1 cup" },
      { name: "salsa", quantity: "1/2 cup" },
    ],
    instructions: [
      "Cook ground beef with taco seasoning until browned.",
      "Warm taco shells in oven.",
      "Fill shells with beef, lettuce, and salsa.",
      "Serve with toppings of choice."
    ],
    cookTime: 15,
    servings: 2,
    difficulty: "Easy",
    description: "Crispy taco shells filled with seasoned beef and fresh toppings.",
    tags: ["Mexican", "Quick", "Street Food"],
    isFavorite: true,
  },
  {
    id: 13,
    name: "Tomato Basil Soup",
    type: "lunch",
    ingredients: [
      { name: "ripe tomatoes", quantity: "4 large" },
      { name: "onion", quantity: "1" },
      { name: "garlic cloves", quantity: "2" },
      { name: "vegetable broth", quantity: "2 cups" },
      { name: "fresh basil", quantity: "1/4 cup" },
    ],
    instructions: [
      "Sauté onion and garlic until soft.",
      "Add chopped tomatoes and broth, simmer 15 minutes.",
      "Blend until smooth, return to pot.",
      "Stir in fresh basil and serve hot."
    ],
    cookTime: 25,
    servings: 3,
    difficulty: "Easy",
    description: "Creamy tomato soup with fresh basil, perfect comfort food.",
    tags: ["Soup", "Vegetarian", "Comfort Food", "Healthy"],
    isFavorite: false,
  },
  {
    id: 14,
    name: "Shrimp Fried Rice",
    type: "dinner",
    ingredients: [
      { name: "cooked rice", quantity: "3 cups" },
      { name: "shrimp", quantity: "200g" },
      { name: "egg", quantity: "2" },
      { name: "soy sauce", quantity: "2 tbsp" },
      { name: "peas and carrots", quantity: "1 cup" },
    ],
    instructions: [
      "Scramble eggs and set aside.",
      "Sauté shrimp until pink.",
      "Add vegetables and rice, stir-fry 5 minutes.",
      "Stir in soy sauce and scrambled eggs.",
      "Serve hot."
    ],
    cookTime: 15,
    servings: 2,
    difficulty: "Medium",
    description: "Classic fried rice with shrimp, eggs, and vegetables.",
    tags: ["Asian", "Quick", "Seafood"],
    isFavorite: true,
  },
  {
    id: 15,
    name: "Margherita Pizza",
    type: "dinner",
    ingredients: [
      { name: "pizza dough", quantity: "1 base" },
      { name: "tomato sauce", quantity: "1/2 cup" },
      { name: "fresh mozzarella", quantity: "125g" },
      { name: "fresh basil leaves", quantity: "6-8" },
      { name: "olive oil", quantity: "1 tbsp" },
    ],
    instructions: [
      "Preheat oven to 220°C.",
      "Spread tomato sauce on pizza dough.",
      "Top with mozzarella and basil leaves.",
      "Drizzle with olive oil.",
      "Bake for 12–15 minutes until crust is golden."
    ],
    cookTime: 20,
    servings: 2,
    difficulty: "Medium",
    description: "Classic Italian pizza with mozzarella, tomato, and basil.",
    tags: ["Italian", "Vegetarian", "Oven"],
    isFavorite: false,
  },
  {
    id: 16,
    name: "Falafel Wrap",
    type: "lunch",
    ingredients: [
      { name: "falafel balls", quantity: "6" },
      { name: "pita bread", quantity: "2" },
      { name: "tahini sauce", quantity: "2 tbsp" },
      { name: "cucumber", quantity: "1/2 cup sliced" },
      { name: "tomato", quantity: "1/2 cup diced" },
    ],
    instructions: [
      "Warm pita bread.",
      "Fill with falafel, cucumber, and tomato.",
      "Drizzle tahini sauce on top.",
      "Wrap tightly and serve."
    ],
    cookTime: 10,
    servings: 2,
    difficulty: "Easy",
    description: "Middle Eastern wrap with crispy falafel and fresh veggies.",
    tags: ["Middle Eastern", "Vegetarian", "Street Food"],
    isFavorite: true,
  },
  {
    id: 17,
    name: "Pancakes",
    type: "breakfast",
    ingredients: [
      { name: "flour", quantity: "1 cup" },
      { name: "milk", quantity: "1 cup" },
      { name: "egg", quantity: "1" },
      { name: "baking powder", quantity: "1 tsp" },
      { name: "syrup", quantity: "to serve" },
    ],
    instructions: [
      "Mix flour, baking powder, milk, and egg into a smooth batter.",
      "Pour batter onto a hot pan, cook until bubbles form, then flip.",
      "Serve warm with syrup."
    ],
    cookTime: 15,
    servings: 2,
    difficulty: "Easy",
    description: "Fluffy breakfast pancakes perfect with syrup.",
    tags: ["Breakfast", "Quick", "Sweet"],
    isFavorite: false,
  },
  {
    id: 18,
    name: "Lentil Curry",
    type: "dinner",
    ingredients: [
      { name: "red lentils", quantity: "1 cup" },
      { name: "onion", quantity: "1" },
      { name: "garlic cloves", quantity: "3" },
      { name: "curry powder", quantity: "2 tbsp" },
      { name: "coconut milk", quantity: "1 can" },
    ],
    instructions: [
      "Sauté onion and garlic until fragrant.",
      "Stir in curry powder and lentils.",
      "Add coconut milk and simmer until lentils are tender.",
      "Serve hot with rice."
    ],
    cookTime: 30,
    servings: 3,
    difficulty: "Medium",
    description: "Hearty vegetarian curry with lentils and coconut milk.",
    tags: ["Indian", "Vegan", "Comfort Food"],
    isFavorite: true,
  },
  {
    id: 19,
    name: "Caesar Salad",
    type: "lunch",
    ingredients: [
      { name: "romaine lettuce", quantity: "1 head" },
      { name: "croutons", quantity: "1 cup" },
      { name: "parmesan cheese", quantity: "1/4 cup" },
      { name: "Caesar dressing", quantity: "3 tbsp" },
      { name: "grilled chicken", quantity: "150g" },
    ],
    instructions: [
      "Chop romaine lettuce and place in a bowl.",
      "Add croutons, parmesan, and chicken slices.",
      "Drizzle with Caesar dressing and toss well.",
      "Serve immediately."
    ],
    cookTime: 10,
    servings: 2,
    difficulty: "Easy",
    description: "Classic Caesar salad with grilled chicken and crunchy croutons.",
    tags: ["Salad", "Healthy", "Quick"],
    isFavorite: false,
  },
  {
    id: 20,
    name: "Butter Chicken",
    type: "dinner",
    ingredients: [
      { name: "chicken thighs", quantity: "300g" },
      { name: "butter", quantity: "2 tbsp" },
      { name: "tomato puree", quantity: "1 cup" },
      { name: "cream", quantity: "1/2 cup" },
      { name: "garam masala", quantity: "1 tbsp" },
    ],
    instructions: [
      "Cook chicken pieces until browned.",
      "Add butter, tomato puree, and spices.",
      "Stir in cream and simmer until sauce thickens.",
      "Serve with naan or rice."
    ],
    cookTime: 35,
    servings: 3,
    difficulty: "Medium",
    description: "Rich and creamy Indian butter chicken curry.",
    tags: ["Indian", "Comfort Food", "Dinner"],
    isFavorite: true,
  },
  {
    id: 21,
    name: "Ratatouille",
    type: "dinner",
    ingredients: [
      { name: "eggplant", quantity: "1" },
      { name: "zucchini", quantity: "1" },
      { name: "bell pepper", quantity: "1" },
      { name: "tomato", quantity: "2" },
      { name: "olive oil", quantity: "2 tbsp" },
    ],
    instructions: [
      "Slice all vegetables thinly.",
      "Arrange in a baking dish alternating layers.",
      "Drizzle with olive oil and season.",
      "Bake at 180°C for 40 minutes."
    ],
    cookTime: 45,
    servings: 3,
    difficulty: "Medium",
    description: "Classic French vegetable stew baked in layers.",
    tags: ["French", "Vegetarian", "Oven"],
    isFavorite: false,
  },
  {
    id: 22,
    name: "Grilled Salmon",
    type: "dinner",
    ingredients: [
      { name: "salmon fillets", quantity: "2" },
      { name: "lemon juice", quantity: "2 tbsp" },
      { name: "garlic powder", quantity: "1 tsp" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "dill", quantity: "1 tsp" },
    ],
    instructions: [
      "Season salmon with lemon juice, garlic, and dill.",
      "Brush with olive oil.",
      "Grill for 6–8 minutes until cooked through.",
      "Serve with vegetables."
    ],
    cookTime: 15,
    servings: 2,
    difficulty: "Easy",
    description: "Juicy salmon fillets grilled with lemon and herbs.",
    tags: ["Seafood", "Healthy", "Quick"],
    isFavorite: true,
  },
  {
    id: 23,
    name: "Chili Con Carne",
    type: "dinner",
    ingredients: [
      { name: "ground beef", quantity: "300g" },
      { name: "kidney beans", quantity: "1 can" },
      { name: "chopped tomatoes", quantity: "1 can" },
      { name: "onion", quantity: "1" },
      { name: "chili powder", quantity: "2 tsp" },
    ],
    instructions: [
      "Sauté onion until soft.",
      "Add beef and cook until browned.",
      "Stir in tomatoes, beans, and chili powder.",
      "Simmer for 25 minutes.",
      "Serve with rice or bread."
    ],
    cookTime: 35,
    servings: 3,
    difficulty: "Medium",
    description: "Spicy and hearty beef chili with beans.",
    tags: ["Mexican", "Spicy", "Comfort Food"],
    isFavorite: false,
  },
  {
    id: 24,
    name: "Pad Thai",
    type: "dinner",
    ingredients: [
      { name: "rice noodles", quantity: "200g" },
      { name: "shrimp", quantity: "150g" },
      { name: "egg", quantity: "1" },
      { name: "bean sprouts", quantity: "1 cup" },
      { name: "peanuts", quantity: "2 tbsp crushed" },
    ],
    instructions: [
      "Soak rice noodles until soft.",
      "Stir-fry shrimp until cooked.",
      "Add noodles, egg, and bean sprouts.",
      "Toss with Pad Thai sauce and top with peanuts."
    ],
    cookTime: 20,
    servings: 2,
    difficulty: "Medium",
    description: "Famous Thai noodle stir-fry with shrimp and peanuts.",
    tags: ["Thai", "Street Food", "Quick"],
    isFavorite: true,
  },
  {
  id: 25,
  name: "Banana Bread",
  type: "dessert",
  ingredients: [
    { name: "ripe bananas", quantity: "3" },
    { name: "all-purpose flour", quantity: "2 cups" },
    { name: "baking soda", quantity: "1 tsp" },
    { name: "salt", quantity: "1/2 tsp" },
    { name: "butter", quantity: "1/2 cup" },
    { name: "sugar", quantity: "3/4 cup" },
    { name: "eggs", quantity: "2" },
    { name: "vanilla extract", quantity: "1 tsp" }
  ],
  instructions: [
    "Preheat oven to 350°F (175°C).",
    "Mash bananas in a large bowl.",
    "Stir in melted butter and sugar until smooth.",
    "Beat in eggs and vanilla extract.",
    "Add flour, baking soda, and salt; mix until just combined.",
    "Pour into greased loaf pan and bake for 60 minutes.",
    "Cool before slicing."
  ],
  cookTime: 65,
  servings: 8,
  difficulty: "Medium",
  description: "Moist and sweet banana bread with a soft crumb and rich flavor.",
  tags: ["Baked", "Sweet", "Dessert", "Family-Friendly"],
  isFavorite: false,
},
{
  id: 26,
  name: "Chicken Stir-Fry",
  type: "dinner",
  ingredients: [
    { name: "chicken breast", quantity: "2" },
    { name: "soy sauce", quantity: "3 tbsp" },
    { name: "ginger", quantity: "1 tbsp grated" },
    { name: "garlic", quantity: "2 cloves" },
    { name: "mixed vegetables", quantity: "3 cups" },
    { name: "sesame oil", quantity: "1 tbsp" },
    { name: "green onions", quantity: "2" }
  ],
  instructions: [
    "Slice chicken into strips.",
    "Heat sesame oil in wok over high heat.",
    "Add garlic and ginger, stir-fry for 30 seconds.",
    "Add chicken and cook until browned.",
    "Add vegetables and soy sauce, stir-fry for 5 minutes.",
    "Garnish with green onions and serve hot."
  ],
  cookTime: 20,
  servings: 3,
  difficulty: "Easy",
  description: "Quick Asian-inspired chicken stir-fry with fresh vegetables.",
  tags: ["Quick", "Healthy", "Asian", "Dinner"],
  isFavorite: true,
},
{
  id: 27,
  name: "Mapo Tofu",
  type: "dinner",
  ingredients: [
    { name: "soft tofu", quantity: "400g" },
    { name: "ground pork", quantity: "200g" },
    { name: "doubanjiang (chili bean paste)", quantity: "2 tbsp" },
    { name: "soy sauce", quantity: "1 tbsp" },
    { name: "chicken broth", quantity: "1/2 cup" },
    { name: "garlic", quantity: "3 cloves" },
    { name: "ginger", quantity: "1 tbsp" },
    { name: "green onions", quantity: "2" },
    { name: "Sichuan peppercorns", quantity: "1 tsp" }
  ],
  instructions: [
    "Heat oil in wok and sauté garlic, ginger, and doubanjiang.",
    "Add ground pork and cook until browned.",
    "Add tofu cubes and gently stir.",
    "Pour in chicken broth and soy sauce, simmer for 5 minutes.",
    "Sprinkle with Sichuan peppercorns and green onions before serving."
  ],
  cookTime: 20,
  servings: 4,
  difficulty: "Medium",
  description: "Spicy Sichuan tofu dish with ground pork and numbing peppercorns.",
  tags: ["Chinese", "Spicy", "Dinner", "Tofu"],
  isFavorite: false,
},
{
  id: 28,
  name: "Beef Tacos",
  type: "dinner",
  ingredients: [
    { name: "ground beef", quantity: "1 lb" },
    { name: "taco seasoning", quantity: "2 tbsp" },
    { name: "taco shells", quantity: "8" },
    { name: "lettuce", quantity: "1 cup shredded" },
    { name: "cheddar cheese", quantity: "1 cup shredded" },
    { name: "salsa", quantity: "1/2 cup" },
    { name: "sour cream", quantity: "1/2 cup" }
  ],
  instructions: [
    "Cook ground beef in skillet until browned.",
    "Add taco seasoning and water, simmer for 5 minutes.",
    "Warm taco shells in oven.",
    "Fill shells with beef, lettuce, cheese, salsa, and sour cream.",
    "Serve immediately."
  ],
  cookTime: 25,
  servings: 4,
  difficulty: "Easy",
  description: "Flavorful beef tacos with fresh toppings and crispy shells.",
  tags: ["Mexican", "Quick", "Family-Friendly", "Dinner"],
  isFavorite: false,
},
{
  id: 29,
  name: "Miso Soup",
  type: "dinner",
  ingredients: [
    { name: "miso paste", quantity: "3 tbsp" },
    { name: "dashi broth", quantity: "4 cups" },
    { name: "tofu", quantity: "1/2 cup cubed" },
    { name: "wakame seaweed", quantity: "2 tbsp" },
    { name: "green onions", quantity: "2" }
  ],
  instructions: [
    "Heat dashi broth in a saucepan.",
    "Whisk in miso paste until dissolved.",
    "Add tofu and wakame, simmer for 2 minutes.",
    "Garnish with sliced green onions.",
    "Serve hot."
  ],
  cookTime: 10,
  servings: 2,
  difficulty: "Easy",
  description: "Traditional Japanese miso soup with tofu and seaweed.",
  tags: ["Japanese", "Healthy", "Soup", "Quick"],
  isFavorite: true,
},
{
  id: 30,
  name: "Lentil Curry",
  type: "dinner",
  ingredients: [
    { name: "red lentils", quantity: "1 cup" },
    { name: "onion", quantity: "1 diced" },
    { name: "garlic", quantity: "3 cloves" },
    { name: "ginger", quantity: "1 tbsp grated" },
    { name: "curry powder", quantity: "2 tbsp" },
    { name: "coconut milk", quantity: "1 can" },
    { name: "spinach", quantity: "2 cups" }
  ],
  instructions: [
    "Sauté onion, garlic, and ginger until fragrant.",
    "Add curry powder and stir for 1 minute.",
    "Stir in lentils and coconut milk, simmer for 20 minutes.",
    "Add spinach and cook until wilted.",
    "Serve with rice or naan."
  ],
  cookTime: 35,
  servings: 4,
  difficulty: "Medium",
  description: "Hearty vegan lentil curry with coconut milk and spinach.",
  tags: ["Indian", "Vegan", "Healthy", "Dinner"],
  isFavorite: false,
},
{
  id: 31,
  name: "Blueberry Muffins",
  type: "breakfast",
  ingredients: [
    { name: "all-purpose flour", quantity: "2 cups" },
    { name: "sugar", quantity: "1 cup" },
    { name: "baking powder", quantity: "2 tsp" },
    { name: "salt", quantity: "1/2 tsp" },
    { name: "eggs", quantity: "2" },
    { name: "milk", quantity: "1 cup" },
    { name: "butter", quantity: "1/2 cup" },
    { name: "blueberries", quantity: "1 cup" }
  ],
  instructions: [
    "Preheat oven to 375°F (190°C).",
    "Mix dry ingredients in a bowl.",
    "Beat eggs, milk, and butter in another bowl.",
    "Combine wet and dry ingredients, fold in blueberries.",
    "Spoon batter into muffin tin and bake for 25 minutes."
  ],
  cookTime: 30,
  servings: 12,
  difficulty: "Medium",
  description: "Fluffy muffins bursting with fresh blueberries.",
  tags: ["Baked", "Sweet", "Breakfast", "Snack"],
  isFavorite: true,
},
{
  id: 32,
  name: "Spring Rolls",
  type: "any",
  ingredients: [
    { name: "spring roll wrappers", quantity: "12" },
    { name: "cabbage", quantity: "1 cup shredded" },
    { name: "carrots", quantity: "1/2 cup julienned" },
    { name: "bean sprouts", quantity: "1 cup" },
    { name: "soy sauce", quantity: "1 tbsp" },
    { name: "garlic", quantity: "2 cloves" },
    { name: "ginger", quantity: "1 tsp" },
    { name: "vegetable oil", quantity: "for frying" }
  ],
  instructions: [
    "Stir-fry cabbage, carrots, bean sprouts, garlic, and ginger with soy sauce.",
    "Let filling cool before wrapping.",
    "Place filling in spring roll wrappers and roll tightly.",
    "Heat oil and deep-fry until golden brown.",
    "Serve with dipping sauce."
  ],
  cookTime: 30,
  servings: 6,
  difficulty: "Medium",
  description: "Crispy fried spring rolls with a vegetable filling.",
  tags: ["Chinese", "Appetizer", "Snack", "Fried"],
  isFavorite: true,
},
{
  id: 33,
  name: "Kung Pao Chicken",
  type: "dinner",
  ingredients: [
    { name: "chicken breast", quantity: "2" },
    { name: "soy sauce", quantity: "3 tbsp" },
    { name: "rice vinegar", quantity: "1 tbsp" },
    { name: "cornstarch", quantity: "2 tsp" },
    { name: "dried red chilies", quantity: "6" },
    { name: "peanuts", quantity: "1/3 cup" },
    { name: "bell pepper", quantity: "1 diced" },
    { name: "green onions", quantity: "3" },
    { name: "garlic", quantity: "3 cloves" },
    { name: "ginger", quantity: "1 tbsp" }
  ],
  instructions: [
    "Marinate chicken with soy sauce, vinegar, and cornstarch for 15 minutes.",
    "Heat oil in a wok and fry dried chilies until fragrant.",
    "Add chicken and stir-fry until browned.",
    "Add bell pepper, garlic, and ginger, cook for 2 minutes.",
    "Stir in peanuts and green onions.",
    "Serve hot with rice."
  ],
  cookTime: 25,
  servings: 3,
  difficulty: "Medium",
  description: "Classic Sichuan dish with stir-fried chicken, chilies, and peanuts.",
  tags: ["Chinese", "Spicy", "Dinner", "Stir-Fry"],
  isFavorite: true,
},
{
  id: 34,
  name: "Chocolate Chip Cookies",
  type: "dessert",
  ingredients: [
    { name: "all-purpose flour", quantity: "2 1/4 cups" },
    { name: "baking soda", quantity: "1 tsp" },
    { name: "salt", quantity: "1/2 tsp" },
    { name: "butter", quantity: "1 cup" },
    { name: "sugar", quantity: "3/4 cup" },
    { name: "brown sugar", quantity: "3/4 cup" },
    { name: "eggs", quantity: "2" },
    { name: "vanilla extract", quantity: "1 tsp" },
    { name: "chocolate chips", quantity: "2 cups" }
  ],
  instructions: [
    "Preheat oven to 375°F (190°C).",
    "Mix flour, baking soda, and salt in a bowl.",
    "Cream butter and sugars in another bowl.",
    "Beat in eggs and vanilla extract.",
    "Gradually mix in dry ingredients.",
    "Fold in chocolate chips.",
    "Drop spoonfuls onto baking sheet and bake for 10 minutes."
  ],
  cookTime: 20,
  servings: 24,
  difficulty: "Medium",
  description: "Classic chewy chocolate chip cookies with crisp edges.",
  tags: ["Baked", "Sweet", "Dessert", "Snack"],
  isFavorite: false,
}


];

const TAGS = [
  "Vegetarian",
  "Vegan",
  "Gluten-Free",
  "Quick",
  "Healthy",
  "Dessert",
  "Spicy",
  "Low-Carb",
];

export { SAMPLE_RECIPES, TAGS };
