import { Recipe } from "./MealTypes";

const SAMPLE_RECIPES: Recipe[] = [
  {
    id: "1",
    name: "Overnight Oats with Berries",
    type: "breakfast",
    ingredients: [
      "1/2 cup rolled oats",
      "1/2 cup almond milk",
      "1 tbsp chia seeds",
      "1 tsp honey",
      "1/4 cup mixed berries",
      "1/4 tsp vanilla extract",
    ],
    instructions: [
      "In a jar or bowl, combine oats, chia seeds, and vanilla extract.",
      "Pour in almond milk and stir well to combine all ingredients.",
      "Add honey and stir again until evenly distributed.",
      "Cover and refrigerate overnight or for at least 4 hours.",
      "In the morning, stir the oats and top with fresh mixed berries.",
      "Enjoy cold or let sit at room temperature for 10 minutes before eating.",
    ],
    cookTime: 5,
    servings: 1,
    difficulty: "Easy",
    description:
      "A healthy and delicious breakfast that requires no cooking. Perfect for busy mornings!",
    tags: ["Healthy", "Quick", "Make-ahead", "Vegetarian"],
    isFavorite: true,
  },
  {
    id: "2",
    name: "Mediterranean Quinoa Bowl",
    type: "lunch",
    ingredients: [
      "1 cup quinoa",
      "2 cups vegetable broth",
      "1 cucumber diced",
      "1 cup cherry tomatoes",
      "1/4 red onion",
      "1/2 cup olives",
      "4 oz feta cheese",
      "2 tbsp olive oil",
      "1 lemon juiced",
    ],
    instructions: [
      "Cook quinoa in vegetable broth according to package directions.",
      "While quinoa cooks, dice cucumber and halve cherry tomatoes.",
      "Slice red onion thinly and crumble feta cheese.",
      "Once quinoa is cooked, let it cool for 10 minutes.",
      "Combine all vegetables with cooled quinoa in a large bowl.",
      "Drizzle with olive oil and lemon juice, then toss gently.",
      "Top with crumbled feta and serve immediately.",
    ],
    cookTime: 20,
    servings: 2,
    difficulty: "Easy",
    description:
      "Fresh and nutritious Mediterranean-inspired bowl packed with vegetables and protein.",
    tags: ["Healthy", "Vegetarian", "High Protein", "Mediterranean"],
    isFavorite: false,
  },
  {
    id: "3",
    name: "Honey Garlic Salmon",
    type: "dinner",
    ingredients: [
      "2 salmon fillets",
      "3 tbsp honey",
      "2 tbsp soy sauce",
      "3 cloves garlic minced",
      "1 tsp ginger grated",
      "1 cup jasmine rice",
      "2 cups broccoli florets",
    ],
    instructions: [
      "Preheat oven to 400°F and line a baking sheet with parchment paper.",
      "Cook rice according to package directions.",
      "Mix honey, soy sauce, minced garlic, and grated ginger in a small bowl.",
      "Place salmon fillets on prepared baking sheet and brush with half the glaze.",
      "Bake for 12-15 minutes until salmon flakes easily with a fork.",
      "Meanwhile, steam broccoli for 4-5 minutes until tender-crisp.",
      "Brush salmon with remaining glaze and serve over rice with steamed broccoli.",
    ],
    cookTime: 25,
    servings: 2,
    difficulty: "Medium",
    description:
      "Perfectly glazed salmon with a sweet and savory honey garlic sauce.",
    tags: ["High Protein", "Gluten-free", "Healthy"],
    isFavorite: false,
  },
  {
    id: "4",
    name: "Avocado Toast Deluxe",
    type: "breakfast",
    ingredients: [
      "2 slices sourdough bread",
      "1 ripe avocado",
      "4-5 cherry tomatoes",
      "2 oz feta cheese",
      "1 tsp everything bagel seasoning",
      "1/2 lemon",
    ],
    instructions: [
      "Toast sourdough bread slices until golden brown.",
      "Mash avocado in a bowl with a squeeze of lemon juice.",
      "Slice cherry tomatoes in half and crumble feta cheese.",
      "Spread mashed avocado evenly on toast slices.",
      "Top with halved cherry tomatoes and crumbled feta.",
      "Sprinkle everything bagel seasoning on top and serve immediately.",
    ],
    cookTime: 5,
    servings: 1,
    difficulty: "Easy",
    description:
      "Elevated avocado toast with fresh toppings and a burst of flavor.",
    tags: ["Quick", "Vegetarian", "Healthy"],
    isFavorite: false,
  },
  {
    id: "5",
    name: "Thai-Style Chicken Curry",
    type: "dinner",
    ingredients: [
      "1 lb chicken thighs cut in pieces",
      "1 can coconut milk",
      "3 tbsp red curry paste",
      "1 bell pepper sliced",
      "1 cup bamboo shoots",
      "1/2 cup Thai basil leaves",
      "2 cups jasmine rice",
    ],
    instructions: [
      "Cook jasmine rice according to package directions and keep warm.",
      "Heat a large skillet over medium-high heat and add chicken pieces.",
      "Cook chicken for 5-6 minutes until browned on all sides.",
      "Add red curry paste and stir for 1 minute until fragrant.",
      "Pour in coconut milk and bring to a gentle simmer.",
      "Add bell pepper and bamboo shoots, simmer for 15-20 minutes.",
      "Stir in Thai basil leaves and cook for 2 more minutes.",
      "Serve hot over jasmine rice.",
    ],
    cookTime: 35,
    servings: 4,
    difficulty: "Medium",
    description:
      "Aromatic and creamy Thai curry with tender chicken and vegetables.",
    tags: ["Spicy", "Asian", "High Protein"],
    isFavorite: false,
  },
  {
    id: "6",
    name: "Greek Yogurt Parfait",
    type: "breakfast",
    ingredients: [
      "1 cup Greek yogurt",
      "1/4 cup granola",
      "1/2 cup mixed berries",
      "1 tbsp honey",
      "4-5 fresh mint leaves",
    ],
    instructions: [
      "Layer half the Greek yogurt in the bottom of a glass or bowl.",
      "Add half the mixed berries over the yogurt layer.",
      "Drizzle with half the honey evenly.",
      "Add a layer of granola for crunch.",
      "Repeat layers with remaining yogurt, berries, and honey.",
      "Top with fresh mint leaves and serve immediately.",
    ],
    cookTime: 3,
    servings: 1,
    difficulty: "Easy",
    description:
      "Protein-rich breakfast parfait with layers of creamy yogurt and crunchy granola.",
    tags: ["Quick", "High Protein", "Healthy", "Vegetarian"],
    isFavorite: true,
  },
];

const TAGS = [
  "Vegetarian",
  "Vegan",
  "Gluten-Free",
  "Quick",
  "Healthy",
  "Dessert",
  "Spicy",
  "Low-Carb",
];

export { SAMPLE_RECIPES, TAGS };
